name: acoms_app
description: "ACOMS Mobile App"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  fl_chart: ^1.2.0
  flutter:
    sdk: flutter
  flutter_local_notifications: ^19.4.2
  http: ^1.6.0
  intl: ^0.20.2
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Alliance2
      fonts:
        - asset: fonts/Alliance2-Regular.otf
    - family: OCR-B
      fonts:
        - asset: fonts/OCR-B.otf
